apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: javaexpress/user-service:latest
          ports:
          - containerPort: 8085
          env:
          - name: DB_HOST
            value: userdb.cxkwc0qo62hy.ap-south-1.rds.amazonaws.com
          - name: DB_NAME
            value: ecomuserms
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: javaexpress1122
          - name: DB_PORT
            value: "3306"                   
          - name: SPRING_APPLICATION_NAME
            value: user-service
          - name: SPRING_PROFILES_ACTIVE
            value: cloud
          - name: EUREKA_SERVER
            value: eureka-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-api
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
