apiVersion: v1
kind: Service
metadata:
  name: user-service-api
spec:
  selector:
    app: user-service
    version: green   # ✅ Change to 'green' when switching
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
